[relabel]
allow-unauthenticated = ["bug", "invalid", "question", "enhancement"]

[assign]

[note]

[concern]
labels = ["has-concerns"]

[major-change]
enabling_label = "major-change"
meeting_label = "to-announce"
second_label = "final-comment-period"
concerns_label = "has-concerns"
accept_label = "major-change-accepted"
waiting_period = 1
auto_closing = true
# can be found by looking for the first number in URLs, e.g. https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler
zulip_stream = 224082
zulip_ping = "Urgau"

[major-change.tracking-issue-template]
repository = "triagebot"
title = "Test tracking issue for MCP#${mcp_number}"
body = """
Multi line body for ${mcp_issue}: ${mcp_title}

Created by ${mcp_author}
"""
labels = ["A-mcp"]

[ping.wg-meta]
message = """\
This is just testing some functionality, please ignore this ping.
"""
label = "help wanted"

[review-changes-since]
